enum Character{
  absol('assets/stat-absol.png'),
  aegislash('assets/stat-aegislash.png'),
  alolanNinetales('assets/stat-alolan-ninetales.png'),
  azumarill('assets/stat-azumarill.png'),
  blastoise('assets/stat-blastoise.png'),
  blissey('assets/stat-blissey.png'),
  buzzwole('assets/stat-buzzwole.png'),
  charizard('assets/stat-charizard.png'),
  cinderace('assets/stat-cinderace.png'),
  cramorant('assets/stat-cramorant.png'),
  crustle('assets/stat-crustle.png'),
  decidueye('assets/stat-decidueye.png'),
  delphox('assets/stat-delphox.png'),
  dragonite('assets/stat-dragonite.png'),
  duraludon('assets/stat-duraludon.png'),
  eldegoss('assets/stat-eldegoss.png'),
  espeon('assets/stat-espeon.png'),
  garchomp('assets/stat-garchomp.png'),
  gardevoir('assets/stat-gardevoir.png'),
  gengar('assets/stat-gengar.png'),
  glaceon('assets/stat-glaceon.png'),
  greedent('assets/stat-greedent.png'),
  greninja('assets/stat-greninja.png'),
  hoopa('assets/stat-hoopa.png'),
  lucario('assets/stat-lucario.png'),
  machamp('assets/stat-machamp.png'),
  mamoswine('assets/stat-mamoswine.png'),
  mrMime('assets/stat-mr-mime.png'),
  pikachu('assets/stat-pikachu.png'),
  slowbro('assets/stat-slowbro.png'),
  snorlax('assets/stat-snorlax.png'),
  sylveon('assets/stat-sylveon.png'),
  talonflame('assets/stat-talonflame.png'),
  trevenant('assets/stat-trevenant.png'),
  tsareena('assets/stat-tsareena.png'),
  venusaur('assets/stat-venusaur.png'),
  wigglytuff('assets/stat-wigglytuff.png'),
  zeraora('assets/stat-zeraora.png');
  final String path;
  const Character(this.path);
}

